### ISSUE TITLE
Default message for validate should be recognised

### ISSUE THREAD

**Issue by olawalejuwonm** [AnechaS/mongoose-validation-error-message-handler#1]
Thanks for this library. It's quite help
![image](https://user-images.githubusercontent.com/52759812/191556885-78734557-b946-4cf3-90f6-64a9d38c1396.png)
For a case of the image above where the validator message is customised, it should override the default.

**Comment by AnechaS** [comment]
you can specific flag `original` = true  to use the original message.

example.
```js
const mongoose = require('mongoose');
const mongooseErrorHandler = require('mongoose-validation-error-message-handler');

const schema = new mongoose.Schema({
  name: {
    type: String,
    validate: {
      validator: v => !!v.trim().length,
      message: 'name is empty'
    }
  },
});

const model = mongoose.model('person', schema);

const object = new model({});
object.save((err, doc) => {
  if (err) {
    const error = mongooseErrorHandler(err, {
      paths: {
        name: { original: true },
      }
    });
  }
});
```

**Comment by olawalejuwonm** [comment]
I'm using it in error handler not like the above

**Comment by AnechaS** [comment]
How do you handle error?

**Comment by olawalejuwonm** [comment]
It's handled in an error handler, when next is called
